sudo: true
language: c
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.stack"
matrix:
  include:
  - env: RELEASEOS="Windows" ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3"
  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly"
  - env: RELEASEOS="MacOS" ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3 osx"
    os: osx
  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly osx"
    os: osx
  allow_failures:
  - env: ARGS="--resolver nightly"
before_install:
- unset CC
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
install:
- if [ -f configure.ac ]; then autoreconf -i; fi
- stack test --no-terminal --install-ghc $ARGS --only-dependencies --ghc-options="-O2"
script:
- stack install --test --no-terminal $ARGS --local-bin-path="." --ghc-options="-O2 -Wall"
after_success: chmod +x .travis/github-release.sh && (.travis/github-release.sh "$RELEASEOS" "$TRAVIS_REPO_SLUG" "$TRAVIS_TAG" Haskell-Console)
