sudo: true
language: c
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.stack"
matrix:
  include:
  - env: RELEASEOS="Windows" ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3"
    addons:
      apt:
        packages:
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons:
      apt:
        packages:
        - libgmp-dev
  - env: RELEASEOS="MacOS" ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3 osx"
    os: osx
  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly osx"
    os: osx
  allow_failures:
  - env: ARGS="--resolver nightly"
before_install:
- unset CC
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
install:
- if [ -f configure.ac ]; then autoreconf -i; fi
- stack test --no-terminal --install-ghc $ARGS --only-dependencies --ghc-options="-O2"
- stack test --no-terminal --install-ghc --arch i386 $ARGS --only-dependencies --ghc-options="-O2"
script:
- mkdir i386
- stack install --test --no-terminal $ARGS --local-bin-path="." --ghc-options="-O2 -Wall"
- stack install --test --no-terminal --arch i386 $ARGS --local-bin-path="i386" --ghc-options="-O2 -Wall"
after_success: chmod +x .travis/github-release.sh && (.travis/github-release.sh "$RELEASEOS" "$TRAVIS_REPO_SLUG" "$TRAVIS_TAG" "Haskell-Console" "i386/Haskell-Console")
