version: 1.0.0.{build}
branches:
  except:
  - test
  - debug
  - runtest
  - onlinetest
skip_tags: true
install:
- ps: >-
    echo "$pwd"

    curl.exe -L https://www.stackage.org/stack/windows-x86_64>./stack.zip

    md stack

    $shellApp = New-Object -ComObject Shell.Application

    $files = $shellApp.NameSpace("$pwd\stack.zip").Items()

    $shellApp.NameSpace("$pwd\stack\").CopyHere($files)

    cp ./stack/stack.exe ./
cache:
- C:\Users\appveyor\AppData\Roaming\stack
- C:\Users\appveyor\AppData\Local\Programs\stack
- C:\mingw\msys
build_script:
- ps: .\stack install --test --no-terminal --resolver lts-6 --local-bin-path="." --ghc-options="-O2 -Wall"
test: off