version: 1.1.{build}
branches:
  except:
  - test
  - debug
  - runtest
  - onlinetest
skip_tags: true
install:
- cmd: "cd\nmd haskell\ncd haskell\nappveyor DownloadFile \"https://raw.githubusercontent.com/YoungIsSimple/Object-Release/1/stack.sfx.exe\" -FileName \"stack.exe\" \nstack.exe\ncd .."
cache:
- C:\Users\appveyor\AppData\Roaming\stack
- C:\Users\appveyor\AppData\Local\Programs\stack
- C:\mingw\msys
build_script:
- cmd: '"c:\haskell\stack.exe" build'
test_script:
- cmd: test.bat