version: 1.0.{build}
skip_tags: true
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
- C:\Users\appveyor\AppData\Roaming\stack
- C:\Users\appveyor\AppData\Local\Programs\stack
- c:\mingw\msys
- C:\msys64
build_script:
- cmd: "cd\ncd /d c:\nmd haskell\ncd haskell\nappveyor DownloadFile \"https://raw.githubusercontent.com/YoungIsSimple/Object-Release/1/stack.sfx.exe\" -FileName \"stack.exe\" \nstack.exe\n\"c:\\haskell\\stack.exe\" --install-ghc build"
test: off